from __future__ import annotations

from pathlib import Path
from typing import Any, Mapping

import yaml

from mpres.scaffolds import ensure_yaml
from mpres.state import REVIEW_CHANNELS
from mpres.util import (
    MPresError,
    relative_display,
    task_path,
    utc_now,
    write_json_atomic,
    write_yaml_atomic,
)

REVIEW_AGGREGATION_ACTOR = "review-aggregation-job"
RELEASE_ACTOR = "release-job"


def _structured_job_template(
    root: Path,
    filename: str,
    presentation_id: str,
    fallback: dict[str, Any],
) -> dict[str, Any]:
    path = root / "templates" / "structured" / filename
    if not path.is_file():
        return fallback
    value = yaml.safe_load(
        path.read_text(encoding="utf-8").replace("[[PRESENTATION_ID]]", presentation_id)
    )
    if not isinstance(value, dict):
        raise MPresError(f"Mechanical job template must contain a mapping: {path}")
    return value


def control_plane_root(root: Path, slug: str) -> Path:
    return task_path(root, slug) / "control-plane"


def review_aggregation_root(root: Path, slug: str, presentation_id: str) -> Path:
    return control_plane_root(root, slug) / "review-aggregation" / presentation_id


def release_workspace(root: Path, slug: str, presentation_id: str) -> Path:
    return control_plane_root(root, slug) / "release" / presentation_id


def prepare_review_aggregation_job(root: Path, slug: str, presentation_id: str) -> Path:
    """Materialize a deterministic control-plane job, never a model assignment."""

    directory = review_aggregation_root(root, slug, presentation_id)
    directory.mkdir(parents=True, exist_ok=True)
    job = directory / "job.yaml"
    if job.is_file():
        from mpres.util import read_yaml

        existing = read_yaml(job)
        if not isinstance(existing, dict):
            raise MPresError(f"Review aggregation job is malformed: {job}")
        expected = {
            "job": "review-aggregation",
            "implementation": "python-control-plane",
            "model_runtime": None,
            "presentation_id": presentation_id,
        }
        mismatches = [key for key, value in expected.items() if existing.get(key) != value]
        if mismatches:
            raise MPresError(
                "Existing review-aggregation job has a different identity and will not be overwritten: "
                + ", ".join(mismatches)
            )
        return job
    ensure_yaml(
        job,
        _structured_job_template(
            root,
            "REVIEW-AGGREGATION-JOB.template.yaml",
            presentation_id,
            {
                "schema_version": 1,
                "job": "review-aggregation",
                "implementation": "python-control-plane",
                "model_runtime": None,
                "presentation_id": presentation_id,
                "required_channels": list(REVIEW_CHANNELS),
                "status": "waiting_for_channel_receipts",
            },
        )
        | {"created_utc": utc_now()},
    )
    return job


def require_review_aggregation_job(root: Path, slug: str, presentation_id: str) -> dict[str, Any]:
    path = review_aggregation_root(root, slug, presentation_id) / "job.yaml"
    from mpres.util import read_yaml

    value = read_yaml(path)
    if not isinstance(value, dict):
        raise MPresError(f"Review aggregation job is malformed: {path}")
    if value.get("job") != "review-aggregation" or value.get("model_runtime") is not None:
        raise MPresError(f"Review aggregation must be a runtime-free control-plane job: {path}")
    return value


def mechanical_aggregate_markdown(
    presentation_id: str,
    *,
    source_submissions: Mapping[str, str],
    findings: list[dict[str, Any]],
) -> str:
    """Generate the aggregate report from validated immutable channel receipts."""

    counts = {channel: 0 for channel in REVIEW_CHANNELS}
    for finding in findings:
        channel = str(finding.get("channel") or "")
        if channel in counts:
            counts[channel] += 1
    lines = [
        f"# Mechanical review aggregate: {presentation_id}",
        "",
        "This report was generated by the Python control plane from the five validated, immutable specialist-review submissions. No review-coordinator model was launched.",
        "",
        f"- Required channels received: {len(source_submissions)}/{len(REVIEW_CHANNELS)}",
        f"- Total findings routed to the deck revision author: {len(findings)}",
        "- Post-revision reviewer verification: none",
        "",
        "## Channel receipts",
        "",
    ]
    for channel in REVIEW_CHANNELS:
        lines.extend(
            [
                f"### {channel}",
                "",
                f"- Submission: `{source_submissions[channel]}`",
                f"- Findings: {counts[channel]}",
                "",
            ]
        )
    lines.extend(
        [
            "## Routing decision",
            "",
            "Every validated finding is preserved verbatim in the canonical findings registry and routed to one deck-revision-author. Original lesson-author threads remain closed. This aggregate does not judge whether later edits resolve a finding.",
            "",
        ]
    )
    return "\n".join(lines)


def complete_review_aggregation_job(
    root: Path,
    slug: str,
    presentation_id: str,
    *,
    aggregate_report: Path,
    findings_registry: Path,
    decision: Path,
    finding_count: int,
) -> Path:
    directory = review_aggregation_root(root, slug, presentation_id)
    directory.mkdir(parents=True, exist_ok=True)
    receipt = directory / "receipt.json"
    write_json_atomic(
        receipt,
        {
            "schema_version": 1,
            "job": "review-aggregation",
            "implementation": "python-control-plane",
            "model_runtime": None,
            "presentation_id": presentation_id,
            "status": "complete",
            "completed_utc": utc_now(),
            "finding_count": finding_count,
            "outputs": {
                "aggregate_report": relative_display(aggregate_report, root),
                "findings_registry": relative_display(findings_registry, root),
                "decision": relative_display(decision, root),
            },
        },
    )
    job_path = directory / "job.yaml"
    if job_path.is_file():
        from mpres.util import read_yaml

        job = read_yaml(job_path)
        if isinstance(job, dict):
            job["status"] = "complete"
            job["completed_utc"] = utc_now()
            job["receipt"] = relative_display(receipt, root)
            write_yaml_atomic(job_path, job)
    return receipt


def prepare_release_job(root: Path, slug: str, presentation_id: str) -> Path:
    """Create the mechanical release manifest inside the release workspace."""

    ready = release_workspace(root, slug, presentation_id)
    ready.mkdir(parents=True, exist_ok=True)
    job = ready / "job.yaml"
    if job.is_file():
        from mpres.util import read_yaml

        existing = read_yaml(job)
        if not isinstance(existing, dict):
            raise MPresError(f"Release job is malformed: {job}")
        expected = {
            "job": "release",
            "implementation": "python-control-plane",
            "model_runtime": None,
            "presentation_id": presentation_id,
        }
        mismatches = [key for key, value in expected.items() if existing.get(key) != value]
        if mismatches:
            raise MPresError(
                "Existing release job has a different identity and will not be overwritten: "
                + ", ".join(mismatches)
            )
        return job
    ensure_yaml(
        job,
        _structured_job_template(
            root,
            "RELEASE-JOB.template.yaml",
            presentation_id,
            {
                "schema_version": 1,
                "job": "release",
                "implementation": "python-control-plane",
                "model_runtime": None,
                "presentation_id": presentation_id,
                "status": "release_ready",
                "required_actions": [
                    "render_release_source",
                    "validate_release_reports",
                    "copy_pdf_and_source_to_deliverables",
                    "write_release_receipt",
                ],
            },
        )
        | {"created_utc": utc_now()},
    )
    return job


def require_release_job(root: Path, slug: str, presentation_id: str) -> dict[str, Any]:
    from mpres.util import read_yaml

    path = release_workspace(root, slug, presentation_id) / "job.yaml"
    value = read_yaml(path)
    if not isinstance(value, dict):
        raise MPresError(f"Release job is malformed: {path}")
    if value.get("job") != "release" or value.get("model_runtime") is not None:
        raise MPresError(f"Release must be a runtime-free control-plane job: {path}")
    return value


def complete_release_job(
    root: Path,
    slug: str,
    presentation_id: str,
    *,
    release_record: Path,
    deliverable: Path,
) -> Path:
    ready = release_workspace(root, slug, presentation_id)
    receipt = ready / "receipt.json"
    write_json_atomic(
        receipt,
        {
            "schema_version": 1,
            "job": "release",
            "implementation": "python-control-plane",
            "model_runtime": None,
            "presentation_id": presentation_id,
            "status": "complete",
            "completed_utc": utc_now(),
            "release_record": relative_display(release_record, root),
            "deliverable": relative_display(deliverable, root),
        },
    )
    job_path = ready / "job.yaml"
    if job_path.is_file():
        from mpres.util import read_yaml

        job = read_yaml(job_path)
        if isinstance(job, dict):
            job["status"] = "complete"
            job["completed_utc"] = utc_now()
            job["receipt"] = relative_display(receipt, root)
            write_yaml_atomic(job_path, job)
    return receipt
